### ISSUE TITLE
Missing documentation on config files

### ISSUE THREAD

**Issue by SgtChrome** [CLEARSY/b2rust#2]
I want to give a big thank you to the contributors of this library, I am really looking forward to working with Atelier B and b2rust.

Would you be able to provide an example or any documentation for the config files needed, in particular for `b2rust_types.cfg`, `b2rust_operations.cfg`, `b2rust_exceptions.cfg`? I do apologize in case I missed it, but it doesn't appear to be obvious how to generate them or how they are supposed to be structured.

Thank you for your consideration.

**Comment by dde-cls** [comment]
Thank you for your interest and your kind words!

There is information on the different configuration files in the user manual, placed in the `doc` directory. 

Please let use know if this is sufficient or not.

**Comment by SgtChrome** [comment]
Thanks a lot, I knew I had to have overlooked it!

I'd like to humbly suggest the following sentence be added to the top-level README.md introduction chapter in case you deem it helpful for other people like me, who can't see the forest for the trees. I'll close the issue.

```markdown
The structure of the configuration files is documented in the [user manual](doc/usermanual.md), 
examples are provided in the directory [files](files).
```

**Comment by dde-cls** [comment]
I have included your sentence into the README file. Thank you for the contribution!
